@startmindmap
+ Безопасность данных
'---------------------------------------------------
++[#lightblue] Публичные данные

+++ Публичная информация о компании
++++[#yellow] Искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб

+++ Публичные предложения (каталог квартир)
++++[#orange] Искажение данных \n риск - значительный
+++++[#lightgreen] Репутационный ущерб, Снижение продаж

+++ Публичные маркетинговые материалы
++++[#yellow] Искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, снижение эффективности маркетинга

+++ Данные онлайн-туров
++++[#yellow] Искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб
'---------------------------------------------------
++[#lightblue] Внутренние данные

+++ Информация публикуемая для пользователей
++++[#yellow] утечка данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб
++++[#yellow] искажение данных, потеря данных \n риск - незначительный
+++++[#lightgreen] Снижение лояльности клиентов


+++ Оповещения о работах
++++[#yellow] утечка данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб
++++[#yellow] искажение данных, потеря данных \n риск - незначительный
+++++[#lightgreen] Снижение лояльности клиентов

+++ Данные CRM
++++[#yellow] утечка данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб


+++ Данные DWH
++++[#orange] утечка данных \n риск - значительный
+++++[#lightgreen] Репутационный ущерб
++++[#yellow] искажение данных \n риск - незначительный
+++++[#lightgreen] Ухудшение эфективности маркетинга

+++ Состояние домофонов и шлагбаумов
++++[#yellow] утечка данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб

+++ Внутренние маркетинговые материалы
++++[#orange] утечка данных \n риск - значительный
+++++[#lightgreen] Возможна утрата конкурентных преимуществ и косвенные финансовые потери
+++ Данные BI и отчётность
++++[#orange] утечка данных \n риск - значительный
+++++[#lightgreen] Возможна утрата конкурентных преимуществ и косвенные финансовые потери

'---------------------------------------------------
++[#lightblue] Конфиденциальные данные

+++ Персональные данные пользователей\n (включая данные транспротных средств)
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Репутационный ущерб, штраф от регулятора
++++[#red] потеря данных, искажение данных \n риск - критический
+++++[#lightgreen] Репутационный ущерб, не заключенные сделки

+++ История оплат
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Репутационный ущерб, штрафы от регулятора
++++ потеря данных, искажение данных \n риск - критический
+++++[#lightgreen] Репутационный ущерб, высокие трудозатраты для восстановления данных

+++ Информация по бронированию
++++[#yellow] утечка данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, возможно снижение продаж
++++[#yellow] потеря данных, искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, возможно снижение продаж

+++ Информация по сделкам
++++[#orange] утечка данных \n риск - значительный
+++++[#lightgreen] Репутационный ущерб, снижение эфекта от маркетинга
++++[#yellow] потеря данных, искажение данных \n риск - незначительный
+++++[#lightgreen] снижение эфекта от маркетинга, высокие трудозатраты для восстановления данных

+++ Информация от IOT устройств пользователя
++++[#orange] утечка данных \n риск - значительный
+++++[#lightgreen] Репутационный ущерб, снижение лояльности пользователей
++++[#yellow] потеря данных, искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, снижение лояльности пользователей

+++ История действий пользователя
++++[#yellow] утечка данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, снижение лояльности пользователей
++++[#yellow] потеря данных, искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, снижение лояльности пользователей

+++ Информация по услугам
++++[#orange] утечка данных \n риск - значительный
+++++[#lightgreen] Репутационный ущерб, снижение лояльности пользователей
++++[#yellow] потеря данных, искажение данных \n риск - незначительный
+++++[#lightgreen] Репутационный ущерб, снижение лояльности пользователей

'---------------------------------------------------
++[#lightblue] Секретные данные

+++ Данные AD
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение вероятности несанкционированного доступа
++++[#red] потеря данных \n риск - критический
+++++[#lightgreen] остановка бизнес процессов

+++ Платежные данные
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Прямые и косвенные финансовые потери
++++[#red] потеря данных \n риск - критический
+++++[#lightgreen] косвенные финансовые потери

+++ Ключ корневого/промежуточного сертификата, которым подписан x509 сертификат домена компании
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Потенциальная возможность MITM атаки на весь TLS трафик

+++ Приватные ключи
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение вероятности несанкционированного доступа

+++ Учетные данные для внешних интеграций
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] косвенные финансовые потери #blue

+++ Учетные данные для доступа сотрудников к инфраструктуре (Пароли/ключи/сертификаты)
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение вероятности несанкционированного доступа


+++ Технологические учетные данные (Например учетки БД c которыми работают приложения)
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение вероятности несанкционированного доступа


+++ Архитектура, аналитика и исходные коды сервисов
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Потеря интелектуальной собственности, Увеличение возможности целевой атаки на логику сервисов

+++ Настройки сервисов и инфраструктуры (включая сетевое оборудование и МЭ)
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение возможности целевой атаки

+++ Архитектура ИБ
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение возможности целевой атаки

+++ Архитектура организации рабочих мест сотрудников компании
++++[#red] утечка данных \n риск - критический
+++++[#lightgreen] Увеличение возможности целевой атаки


@endmindmap